### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte

### ISSUE THREAD

**Issue by mikroskeem** [MrPowerGamerBR/ProtocolSupportSwordBlocking#1]
Woo, I could give your plugin a try finally :)

But it throws ClassCastException when player joins, I guess it is because packet field type is different in 1.12.

Stack trace: https://paste.mikroskeem.eu/babevoguci.rb

**Comment by MrPowerGamerBR** [comment]
Actually it is due to a broken check I made, I fixed this a long time ago but I never bothered submitting an update or updating the source.

Anyway, I fixed the issue if you know how to recompile the source, I will submit an update to Spigot ASAP. :)

**Comment by MrPowerGamerBR** [comment]
However I didn't test this fix in 1.12, if the same error still happens under 1.12, please open a new issue! 😄

**Comment by mikroskeem** [comment]
I made bunch of changes and [threw in exactly the same check](https://github.com/mikroskeem/ProtocolSupportSwordBlocking/commit/1e4b7c94cbda57916e17dd9b09ad98a7ab82700f) into my fork. Everything seemed to work fine.

Also I have working jar under releases, if you're interested.
